# Generated by Django 6.0.3 on 2026-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
